- elb_application_lb:
    name: anible-alb
    security_groups:
      - sg-4146685c
    subnets:
      - subnet-0af51846
      - subnet-5b35683d
      - subnet-4fb2ea6e
    listeners:
      - Protocol: HTTP # Required. The protocol for connections from clients to the load balancer (HTTP or HTTPS) (case-sensitive).
        Port: 80 # Required. The port on which the load balancer is listening.
        # The security policy that defines which ciphers and protocols are supported. The default is the current predefined security policy.
        DefaultActions:
          - Type: forward # Required.
            TargetGroupName: ansible-target
    region: us-east-1
    state: present