-
  name: Install all required dependencies
  apt: 
    name:  ['python3', 'python3-setuptools', 'python3-dev', 'build-essential', 'python3-pip']
    state: present
    # with_items:
    #   - python
    #   - python-setuptools
    #   - python-dev
    #   - build-essential
    #   - python-pip

- name: install boto3
  become: true
  pip:
    name: ['botocore','boto3']
    state: present
    executable: pip3